### PR TITLE
fix FreeBSD build

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
@DiegoMagdaleno I have a feeling that the ninja problem is a cmake bug. Or at least, the cmake package that's available with this version of FreeBSD. I tried in an OpenBSD vm with `cmake -B build -G Ninja' and cmake ran fine (up until it couldn't find 'OpenSSL::Crypto'). In https://github.com/DiegoMagdaleno/BSDCoreUtils/pull/17 I tried a lot of different combinations but ninja was never found.

I don't think ninja is the problem, because I use it in the [rmw CI](https://github.com/theimpossibleastronaut/rmw/blob/dd578e414ffdc70da7d092f34a7d1881ac2764f5/.github/workflows/c-cpp.yml#L117)

In this PR, I switched to building with `make` and cmake ran ok, but the build failed I think for the same reason the macos build is failing atm.

**Comment by andy5995** [comment]
> I tried in an OpenBSD vm with `cmake -B build -G Ninja' and cmake ran fine (up until it couldn't find 'OpenSSL::Crypto'). In #17 I tried a lot of different combinations but ninja was never found.

Odd. I added OpenBSD but get the same results, that Ninja couldn't be found...

**Comment by andy5995** [comment]
btw, you can get a freebsd shell here https://github.com/vmactions/shell-freebsd

**Comment by DiegoMagdaleno** [comment]
I see, thank you for fixing it.

I just need to check if changing the CMake version doesn't cause issues as I use a CMake 3.25 feature.

**Comment by andy5995** [comment]
> I just need to check if changing the CMake version doesn't cause issues as I use a CMake 3.25 feature.

I changed it back. I think 3.25 is available in the FreeBSD vm... We'll see...

**Comment by DiegoMagdaleno** [comment]
Okay that fixes it, thank you!

I'll fix the mtio problem in a more cross-platform way.

**Pull request merged**
